name:                concordium-client
version:             4.2.0
github:              "Concordium/concordium-client"
author:              "Concordium"
maintainer:          "developers@concordium.com"
copyright:           "Concordium"
license-file:        "LICENSE"
license:             "Apache-2.0"
build-type:          Custom
extra-source-files:
- README.md
- ChangeLog.md
- deps/grpc-api/concordium_p2p_rpc.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup == 0.4.*

default-extensions:
- OverloadedStrings
- RecordWildCards
- GeneralizedNewtypeDeriving
- ScopedTypeVariables
- FlexibleContexts
- LambdaCase
- TupleSections

ghc-options: -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Concordium/concordium-client#readme>

flags:
  middleware:
    manual: True
    default: True
  static:
    description: Use static linking.
    manual: True
    default: False

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options:
    - -Wcompat
    - -Werror=missing-fields
    - -Wredundant-constraints
    - -O
  source-dirs:
      src
  dependencies:
    - aeson
    - aeson-pretty
    - ansi-terminal
    - ansi-wl-pprint
    - attoparsec
    - base >=4.7 && <5
    - base16-bytestring
    - base64-bytestring
    - bytestring
    - cereal
    - cborg
    - cborg-json
    - concordium-base
    - containers
    - cryptonite
    - directory
    - filepath
    - optparse-applicative
    - random
    - split
    - mtl
    - text
    - time
    - http2-client-grpc >= 0.7
    - http2-client >= 0.9
    - http2-grpc-types
    - http2-grpc-proto-lens
    - unordered-containers
    - hashable >= 1.2
    - pretty
    - proto-lens == 0.7.*
    - proto-lens-protobuf-types == 0.7.*
    - proto-lens-runtime == 0.7.*
    - microlens-platform
    - transformers
    - uri-encode >= 1.5
    - concurrent-extra >= 0.7
    - async >= 2.2
    - vector >= 0.12
    - string-interpolate
    - scientific
  generated-exposed-modules:
    Proto.ConcordiumP2pRpc
    Proto.ConcordiumP2pRpc_Fields

executables:
  concordium-client:
    main:             Main.hs
    source-dirs:      app

    ghc-options:
      - -Wcompat
      - -Werror=missing-fields
      - -Wredundant-constraints
      - -O

    when:
      - condition: flag(static)
        ld-options:
        - -static

    dependencies:
      - optparse-applicative
      - base
      - concordium-client

  tx-generator:
    main:            Main.hs
    source-dirs:     generator
    ghc-options:
      - -Wcompat
      - -Werror=missing-fields
      - -Wredundant-constraints
      - -O
    when:
      - condition: ! os(windows) 
        # the tool deadlocks on windows when -threaded is used
        ghc-options: -threaded
      - condition: flag(static)
        ld-options:
        - -static
    dependencies:
      - optparse-applicative
      - mtl
      - containers
      - base
      - concordium-client
      - concordium-base
      - bytestring
      - aeson
      - time

  middleware:
    main:             Main.hs
    source-dirs:      middleware
    ghc-options:
      - -threaded
    dependencies:
      - aeson
      - wai-logger
      - bytestring
      - concordium-base
      - containers
      - directory
      - filepath
      - http-conduit
      - http2-client-grpc
      - microlens-platform
      - monad-logger
      - mtl
      - process
      - servant
      - servant-server
      - concordium-client
      - split
      - text
      - time
      - unordered-containers
      - wai
      - wai-cors
      - wai-extra
      - wai-middleware-static
      - warp
      - mtl >= 2.2.2
      - cereal >= 0.5.8
      - transformers
    when:
      - condition: flag(middleware)
        then:
          buildable: true
        else:
          buildable: false

tests:
  concordium-client-test:
    ghc-options:
      - -Wcompat
      - -Werror=missing-fields
      - -Wredundant-constraints
      - -O
    main:             Spec.hs
    source-dirs:      test
    dependencies:
      - concordium-client
      - concordium-base
      - cereal
      - aeson
      - bytestring
      - base64-bytestring
      - containers
      - hspec >= 2.6
      - hspec-expectations >= 0.8
      - HUnit >= 1.6
      - QuickCheck >= 2.13
      - mtl >= 2.2.2
      - text
      - transformers
      - time
      - unordered-containers
      - filepath
      - vector
      - random
