name: Concordium client release

on:
  push:
    branches:
      - lma/release/github_actions
    tags:
     - '*.*.*-*'

env:
  S3_ARN_TEMPLATES: '{
      \"client-linux\": \"s3://distribution.concordium.software/tools/linux/concordium-client_${VERSION}\",
      \"client-macos\": \"s3://distribution.concordium.software/tools/macos/concordium-client_${VERSION}-unsigned.pkg\",
      \"client-windows\": \"s3://distribution.concordium.software/tools/windows/concordium-client_${VERSION}.zip\"
    }'
  AWS_ROLE_TO_ASSUME: 'arn:aws:iam::192549843005:role/github_concordium-client'



jobs:
  validate-preconditions:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Retrieve GitHub OIDC Token and Extract Sub
        id: oidc_token
        run: |
          # Fetch OIDC token from GitHub
          oidc_token=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')

          # Decode the token and extract 'sub' (subject) claim
          sub=$(echo "${oidc_token}" | base64 -d | jq -r '.sub')
          echo "OIDC sub: $sub"
          echo "sub=${sub}" >> "$GITHUB_ENV"
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ steps.auth.outputs.id-token }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::192549843005:role/github_concordium-client"
          role-session-name: ClientPreconditionsSession
          aws-region: "eu-west-1"
