name: Concordium client release

on:
  push:
    branches:
      - lma/release/github_actions
    tags:
     - '*.*.*-*'

env:
  S3_ARN_TEMPLATES: '{
      \"client-linux\": \"s3://distribution.concordium.software/tools/linux/concordium-client_${VERSION}\",
      \"client-macos\": \"s3://distribution.concordium.software/tools/macos/concordium-client_${VERSION}-unsigned.pkg\",
      \"client-windows\": \"s3://distribution.concordium.software/tools/windows/concordium-client_${VERSION}.zip\"
    }'
  AWS_ROLE_TO_ASSUME: 'arn:aws:iam::192549843005:role/github_concordium-client'



jobs:
  validate-preconditions:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: ClientPreconditionsSession
          aws-region: "eu-west-1"
